name: Contracts CI

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'contracts/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'contracts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Clarinet
        uses: hirosystems/setup-clarinet@v1
        with:
          version: '2.4.0'

      - name: Check contracts
        run: clarinet check
        working-directory: ./contracts
